/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "source/fa4.sv:1.1-12.10" *)
module fa4(A, B, Cin, S, Cout);
  (* src = "source/fa4.sv:2.19-2.20" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "source/fa4.sv:2.21-2.22" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "source/fa4.sv:3.13-3.16" *)
  input Cin;
  wire Cin;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] Cin_SB_LUT4_I1_O;
  (* src = "source/fa4.sv:5.14-5.18" *)
  output Cout;
  wire Cout;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] Cout_SB_LUT4_O_I2;
  (* src = "source/fa4.sv:4.20-4.21" *)
  output [3:0] S;
  wire [3:0] S;
  (* hdlname = "fulladder1 A" *)
  (* src = "source/fa.sv:3.13-3.14" *)
  wire \fulladder1.A ;
  (* hdlname = "fulladder1 B" *)
  (* src = "source/fa.sv:3.16-3.17" *)
  wire \fulladder1.B ;
  (* hdlname = "fulladder1 Cin" *)
  (* src = "source/fa.sv:3.19-3.22" *)
  wire \fulladder1.Cin ;
  (* hdlname = "fulladder1 S" *)
  (* src = "source/fa.sv:4.14-4.15" *)
  wire \fulladder1.S ;
  (* hdlname = "fulladder2 A" *)
  (* src = "source/fa.sv:3.13-3.14" *)
  wire \fulladder2.A ;
  (* hdlname = "fulladder2 B" *)
  (* src = "source/fa.sv:3.16-3.17" *)
  wire \fulladder2.B ;
  (* hdlname = "fulladder2 S" *)
  (* src = "source/fa.sv:4.14-4.15" *)
  wire \fulladder2.S ;
  (* hdlname = "fulladder3 A" *)
  (* src = "source/fa.sv:3.13-3.14" *)
  wire \fulladder3.A ;
  (* hdlname = "fulladder3 B" *)
  (* src = "source/fa.sv:3.16-3.17" *)
  wire \fulladder3.B ;
  (* hdlname = "fulladder3 S" *)
  (* src = "source/fa.sv:4.14-4.15" *)
  wire \fulladder3.S ;
  (* hdlname = "fulladder4 A" *)
  (* src = "source/fa.sv:3.13-3.14" *)
  wire \fulladder4.A ;
  (* hdlname = "fulladder4 B" *)
  (* src = "source/fa.sv:3.16-3.17" *)
  wire \fulladder4.B ;
  (* hdlname = "fulladder4 Cout" *)
  (* src = "source/fa.sv:4.17-4.21" *)
  wire \fulladder4.Cout ;
  (* hdlname = "fulladder4 S" *)
  (* src = "source/fa.sv:4.14-4.15" *)
  wire \fulladder4.S ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) B_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(B[2]),
    .I3(A[2]),
    .O(Cout_SB_LUT4_O_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h033f)
  ) Cin_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(Cin),
    .I2(B[0]),
    .I3(A[0]),
    .O(Cin_SB_LUT4_I1_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h80e0)
  ) Cin_SB_LUT4_I1_O_SB_LUT4_I2 (
    .I0(B[1]),
    .I1(A[1]),
    .I2(Cin_SB_LUT4_I1_O[2]),
    .I3(Cin_SB_LUT4_I1_O[3]),
    .O(Cout_SB_LUT4_O_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0ff0)
  ) Cin_SB_LUT4_I1_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(B[2]),
    .I3(A[2]),
    .O(Cin_SB_LUT4_I1_O[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'heee8)
  ) Cout_SB_LUT4_O (
    .I0(B[3]),
    .I1(A[3]),
    .I2(Cout_SB_LUT4_O_I2[2]),
    .I3(Cout_SB_LUT4_O_I2[3]),
    .O(Cout)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc33c)
  ) \fulladder1.S_SB_LUT4_O  (
    .I0(1'h0),
    .I1(Cin),
    .I2(B[0]),
    .I3(A[0]),
    .O(\fulladder1.S )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h3cc3)
  ) \fulladder2.S_SB_LUT4_O  (
    .I0(1'h0),
    .I1(B[1]),
    .I2(A[1]),
    .I3(Cin_SB_LUT4_I1_O[3]),
    .O(\fulladder2.S )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h781e)
  ) \fulladder3.S_SB_LUT4_O  (
    .I0(B[1]),
    .I1(A[1]),
    .I2(Cin_SB_LUT4_I1_O[2]),
    .I3(Cin_SB_LUT4_I1_O[3]),
    .O(\fulladder3.S )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h9996)
  ) \fulladder4.S_SB_LUT4_O  (
    .I0(B[3]),
    .I1(A[3]),
    .I2(Cout_SB_LUT4_O_I2[2]),
    .I3(Cout_SB_LUT4_O_I2[3]),
    .O(\fulladder4.S )
  );
  assign Cout_SB_LUT4_O_I2[1:0] = { A[3], B[3] };
  assign Cin_SB_LUT4_I1_O[1:0] = { A[1], B[1] };
  assign S = { \fulladder4.S , \fulladder3.S , \fulladder2.S , \fulladder1.S  };
  assign \fulladder1.A  = A[0];
  assign \fulladder1.B  = B[0];
  assign \fulladder1.Cin  = Cin;
  assign \fulladder2.A  = A[1];
  assign \fulladder2.B  = B[1];
  assign \fulladder3.A  = A[2];
  assign \fulladder3.B  = B[2];
  assign \fulladder4.A  = A[3];
  assign \fulladder4.B  = B[3];
  assign \fulladder4.Cout  = Cout;
endmodule
